### ISSUE TITLE
Acronyms: JP = John Podesta, TP = Tony Podesta

### ISSUE THREAD

**Issue by colinskow** [qanonmap/qanonmap.github.io#11]
Acronyms: JP = John Podesta, TP = Tony Podesta

Mar 3 2018 20:56:48
Q
!UW.yye1fxo
ID: 9dc69f
544701
The BRIDGE.
187
BRIDGE-2.
@Snowden
Clowns.
The LINK.
Google/YT.
Facebook.
Twitter.
Russia ICBM tech.
HRC open source.
SAP.
JP.
TP.
Highest levels of US-G.
U1.
NK.
WHY would Russia tell the world?
Why?
Why is SR back in the news?
Why?
Why is SESSIONS acting weak?
Why?
IG report?
No legit leaks.
MSM staging narrative.
IG appointed by SESSIONS for?
Why?
Why?
Enjoy the show.
Dead cat bounce.
Q

**Comment by qanonmap** [comment]
Thank you. Added.
