### ISSUE TITLE
Answers button gone

### ISSUE THREAD

**Issue by colinskow** [qanonmap/qanonmap.github.io#5]
The "Answers" button seems to have disappeared. I know they are no longer being updated, but they contain really valuable information about the early posts.

I definitely think removing the button is a disservice to the community.

**Comment by qntmpkts** [comment]
False. For any post that has answers, the post will have its own answers button. Only the cumbersome toggle was removed.

**Comment by colinskow** [comment]
How to toggle then?

**Comment by colinskow** [comment]
https://github.com/qanonmap/qanonmap.github.io/blob/master/index.js#L21

**Comment by qanonmap** [comment]
Answers can be found on posts with answers. This is not an issue.

**Comment by colinskow** [comment]
Appearing now... Not sure why they weren't earlier. Thanks anyway for your attention!
