### ISSUE TITLE
Acronym: OS = oversight

### ISSUE THREAD

**Issue by colinskow** [qanonmap/qanonmap.github.io#9]
Acronym: OS = oversight

466048
>>465930
How do you break up something this big?
What happens if low/mid/senior (non corrupt) Patriots learn they were sold out?
What happens?
Who is waiting with open arms w/ a plan to reorg under a single entity with direct OS by trusted Patriots?
Who are trusted Patriots who understand intel collection?
Q

**Comment by qanonmap** [comment]
Added.
